apiVersion: apps/v1
kind: Deployment
metadata:
  name: pexels-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pexels-app
  template:
    metadata:
      labels:
        app: pexels-app
    spec:
      containers:
      - name: app
        image: docker.io/sushant911/pexels-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: Pexels_Token          
          valueFrom:
            secretKeyRef:
              name: pexels-secret
              key: token
        resources:
          requests:
            cpu: "0.25"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pexels-svc
spec:
  type: LoadBalancer  
  selector:
    app: pexels-app
  ports:
    - port: 80
      targetPort: 8080
